trigger:
  - main

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'my-azure-connection'
  webAppName: 'node-web-ghemarc'
  packageDirectory: '$(System.DefaultWorkingDirectory)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run test
  displayName: 'Run Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(packageDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
    replaceExistingArchive: true
  displayName: 'Archive App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/node-app.zip'
  displayName: 'Deploy to Azure Web App'


